### ISSUE TITLE
remove ground 

### ISSUE THREAD

**Issue by xsy199** [naurril/SUSTechPOINTS#17]
hello naurril:
 thank you for sharing such a great job.
 I wonder know if you have do some job like remove the ground? when i select a box, i find that the ground is really effect the result.
thank you so much!

**Comment by naurril** [comment]
Yes, this tool removes the lowest 0.3m part of the object before calculating dimension/rotation. I tried a few ground removing algorithms and found this one most effective.  

This naive algorithm has the limit that it requires the ground plane to be (almost) parallel to the x-y plane of LiDAR. But sadly in the example scene, this requirement is not met due to the imperfect installation of the LiDAR.

You can try some other dataset, like KITTI or nuScenes. I will upload more examples later.

**Comment by xsy199** [comment]
sorry, i still not understand, that you say you have remove the ground when calculating the dimension,why the ground still included when show box in image?does that mean when you finally give the box dimension and rotation,the 0.3m was added?

**Comment by naurril** [comment]
Yes, 0.3m is added after the calculation

**Comment by naurril** [comment]
If you mean the general ground removal method, you may try the method used by [legoLoam](https://ieeexplore.ieee.org/document/8594299)

**Comment by xsy199** [comment]
thanks, i will try to read it. 
My question is that the ground is always non-parallel. I am thinking if it is possible to remove the ground before importing the pcd file, or add a function to remove the ground first in your tool.
anyway,thank you.
